services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - DB_URL=mongodb://host.docker.internal:27017/angularNode
      - JWT_SECRET=your_jwt_secret
      - JWT_REFRESH_SECRET=your_refresh_secret
    volumes:
      - .:/app
      - /app/node_modules